server:
  port: 8081

spring:
  profiles:
    active: prod
  datasource:
    url: ${DATA_SOURCE_URL}
    username: ${DATA_SOURCE_USERNAME}
    password: ${DATA_SOURCE_PASSWORD}
    ## url: DATA_SOURCE_URL: jdbc:postgresql://dpg-cuuvq4dds78s7387qa6g-a.oregon-postgres.render.com:5432/aws_postgres_bd_pu6c
    ## username: DATA_SOURCE_USERNAME: aws_postgres_bd_pu6c_user
    ## password: DATA_SOURCE_PASSWORD: ZSkHJr002ddgo7FvHoohjPHYgjx5AocZ
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 50

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: info